namespace DrawingCanvas
{
    [bindable]
    [default_interface]
    runtimeclass BrushItemModel 
    {
        BrushItemModel();

        String Name{ get; set; };

        Windows.UI.Xaml.Media.Imaging.BitmapImage Preview{ get; set; };
    }
}
